"""Apply 7 missing longTexts to histoire-chapitres.json"""
import json

main_path = r"C:\Users\louis\Desktop\K&C\Patrimoine & Sens\public\data\histoire-chapitres.json"
with open(main_path, encoding="utf-8") as f:
    data = json.load(f)

missing = {
    86: "L'Armorial general de France, commande par Louis XIV en 1696, est un outil fiscal deguise en recueil heraldique. Le roi a besoin d'argent -- la guerre de la Ligue d'Augsbourg ruine les finances. L'edit de novembre 1696 oblige toute personne, institution ou communaute possedant des armoiries a les faire enregistrer -- moyennant finance. Ceux qui n'en ont pas sont invites a en acquerir. Le juge d'armes Charles-Rene d'Hozier est charge de l'operation.\n\nPour le bailliage de Sens, l'Armorial recense 110 blasons senonais dans le manuscrit francais 32252 de la BnF (pages 36-58). On y trouve les armes de la ville elle-meme, celles du chapitre cathedral, des abbayes (Sainte-Colombe, Saint-Pierre-le-Vif, Saint-Jean), des officiers du bailliage, des marchands et des corporations.\n\nCe qui rend cet armorial precieux pour l'histoire locale, c'est son caractere exhaustif. Contrairement aux nobiliaires qui ne recensent que la noblesse, l'Armorial d'Hozier enregistre tout le monde -- y compris les bourgeois, les artisans, les institutions religieuses. C'est une photographie de la societe senonaise a la fin du XVIIe siecle.\n\nL'armorial revele aussi le couvent des Religieuses Benedictines de Villeneuve-le-Roy (ancien nom de Villeneuve-sur-Yonne), les Ursulines de Sens, la communaute des chirurgiens. Chaque blason raconte un statut social, une pretention, parfois une fiction -- certaines armes ont ete attribuees d'office par Hozier a des gens qui n'en avaient jamais eu, juste pour encaisser la taxe.",

    120: "La caserne Gemeau raconte a elle seule deux siecles d'histoire militaire francaise. Son nom vient d'Auguste Pierre Walbourg Gemeau (1790-1868), un officier napoleonien qui a combattu a Wagram, en Espagne et en Russie. Apres Waterloo, interdit de sejour a Paris comme beaucoup d'anciens de la Grande Armee, il s'installe a Sens ou il finit ses jours.\n\nLes batiments actuels sont construits en 1874, dans la fievre de rearmement qui suit la defaite de 1870 contre la Prusse. Le 89e Regiment d'Infanterie y tient garnison. C'est un regiment de conscrits -- des jeunes hommes de l'Yonne qui font leur service militaire. En 1914, ils partent pour le front. La plupart ne reviendront pas.\n\nApres 1945, l'armee quitte les lieux. Le ministere de l'Interieur transforme la caserne en centre de formation de la police. En 1946, c'est d'abord un centre de formation des motocyclistes. En 1948, les premiers stages de gardiens de la paix debutent. L'Ecole nationale de police de Sens est nee -- elle forme encore aujourd'hui des gardiens de la paix et des cadets de la Republique.\n\nDe la Grande Armee a la police nationale, en passant par les tranchees de 14-18 : la caserne Gemeau a change de mission a chaque generation, mais sa fonction n'a jamais varie -- former des hommes en uniforme au service de l'Etat.",

    132: "Dans les annees 1880-1890, un insecte minuscule -- le phylloxera -- detruit le vignoble francais. Le Senonais n'est pas epargne. Avant le phylloxera, les coteaux autour de Sens etaient couverts de vignes. Le vin senonais n'etait pas grand -- c'etait un vin de pays, acide et leger -- mais il faisait vivre des centaines de familles.\n\nLe phylloxera est un puceron americain arrive en France vers 1860 via des plants importes. Il attaque les racines de la vigne europeenne, qui n'a aucune defense contre lui. En quelques annees, des regions entieres sont devastees. Le Senonais perd ses vignes entre 1885 et 1895.\n\nLa solution existe -- greffer les cepages francais sur des porte-greffes americains resistants -- mais elle est couteuse et technique. Les grands domaines bordelais et bourguignons s'en remettent. Les petits vignerons du Senonais, eux, abandonnent. Ils n'ont pas les moyens de replanter.\n\nC'est un tournant economique majeur pour la region. Quand le vignoble disparait, l'economie locale perd un de ses piliers. Les terres a vignes sont converties en cultures cerealieres ou en paturages. Les familles vigneronnes migrent vers les villes ou se reconvertissent. La physionomie du paysage senonais change definitivement.\n\nAujourd'hui, il ne reste presque rien du vignoble senonais. Quelques micro-cuvees confidentielles, quelques toponymes (les Vignes, le Clos) et le souvenir d'un temps ou Sens avait son vin.",

    135: "L'histoire de la fromagerie Lincet commence a la fin du XIXe siecle dans le Senonais. La famille Lincet, installee dans la region, commence a affiner des fromages a pate molle et croute fleurie -- le Chaource et ce qui deviendra le Brillat-Savarin.\n\nLe Brillat-Savarin est un fromage triple-creme (75% de matiere grasse) cree dans les annees 1890. Mais c'est dans le Senonais que sa production industrielle se developpe, grace au lait abondant des fermes de la Champagne humide et de la vallee de l'Yonne.\n\nLa fromagerie Lincet est devenue le premier producteur mondial de Brillat-Savarin. C'est une success-story industrielle locale qui a traverse le XXe siecle. Le Chaource, quant a lui, est un fromage AOC depuis 1970, puis AOP au niveau europeen.\n\nCe qui est interessant, c'est le lien entre la disparition du vignoble (phylloxera des annees 1890) et l'essor de la fromagerie. Quand les vignes meurent, les terres sont converties en paturages. Plus de vaches = plus de lait = plus de fromage. Le malheur viticole nourrit le succes fromager. C'est un exemple de reconversion economique rurale -- pas planifiee, pas decidee par un ministre, mais emergente, portee par des familles qui s'adaptent.",

    137: "Au tournant du XXe siecle, un mouvement artistique nouveau envahit les facades des villes francaises : l'Art Nouveau. A Sens, le plus bel exemple est l'immeuble du 2 boulevard de Maupeou, construit entre 1907 et 1909.\n\nL'architecte Richardot -- le meme qui construira l'Hotel de Ville -- concoit un immeuble de rapport dont la facade est un manifeste esthetique. Bas-reliefs floraux, balustrades en fer forge ouvrage, grandes baies vitrees, courbes et contre-courbes -- c'est du pur Art Nouveau.\n\nLe sculpteur Delassasseigne realise les decors. L'entrepreneur Coydon utilise une technique alors moderne : la pierre armee (pierre renforcee par du metal), qui permet des porte-a-faux et des decorations impossibles en maconnerie traditionnelle.\n\nL'immeuble est inscrit aux monuments historiques en 2013. C'est le seul immeuble Art Nouveau protege a Sens.\n\nCe qui est remarquable, c'est que cet immeuble existe dans une ville de 25 000 habitants en 1900. Sens n'est ni Paris, ni Nancy, ni Bruxelles -- les capitales reconnues de l'Art Nouveau. Un bourgeois senonais qui fait construire en 1907 veut les memes chimeres et mascarons que les Parisiens. Et il les obtient.",

    138: "En 1902, la France vit les dernieres annees d'un combat politique majeur : la separation de l'Eglise et de l'Etat, votee en 1905. A Sens, ce combat est particulierement intense parce que la ville est le siege d'un archeveche primatial -- l'un des plus anciens et des plus prestigieux de France.\n\nLe maire Lucien Cornet, radical-socialiste, incarne cette lutte. Il est maire depuis 1885 et le restera jusqu'en 1922 -- trente-sept ans. Son grand oeuvre : l'Hotel de Ville, inaugure en 1904, dont le campanile de 56 metres fait face a la cathedrale. Le message est limpide : la Republique repond a l'Eglise.\n\nCornet fait aussi construire des ecoles laiques pour concurrencer les ecoles congreganistes. La loi Combes de 1904 interdit l'enseignement aux congregations religieuses. A Sens, les Ursulines, les Freres des ecoles chretiennes, les soeurs enseignantes sont expulsees de leurs etablissements.\n\nEn 1905, la loi de separation est votee. L'archeveche est expulse du palais archiepiscopal (qui devient musee municipal). L'archeveque se replie dans l'Hotel de Bourrienne, rue de l'Ecrivain, qui sert de siege episcopal jusqu'en 1929.\n\nCe qui rend l'histoire senonaise particuliere, c'est l'intensite du face-a-face. Sens n'est pas n'importe quel eveche -- c'est l'archeveche primatial, celui qui commandait a Paris. La Republique s'attaque ici a un symbole millenaire.",

    158: "En septembre 1939, la France entre en guerre. A Sens, comme partout, les hommes sont mobilises. Mais pendant huit mois, rien ne se passe sur le front -- c'est la drole de guerre. Les soldats attendent dans les casernes et les cantonnements.\n\nGaston Gaudaire, dans son livre Une ville pendant la guerre, decrit cette periode d'attente a Sens. La ville se prepare : on distribue des masques a gaz, on creuse des tranchees-abris dans les jardins publics, on organise la defense passive (couvre-feu, fenetres occultees). Mais l'ennemi ne vient pas.\n\nEn mai-juin 1940, tout bascule. La Wehrmacht perce le front et deferle vers le sud. Le 14 juin, les Allemands entrent dans Paris. Le 15 ou le 16 juin, ils arrivent a Sens. La ville est declaree ville ouverte -- pas de resistance militaire. Les ponts sur l'Yonne sont dynamites par l'armee francaise en retraite, mais les Allemands les traversent a gue.\n\nL'Hotel de Paris et de la Poste est requisitionne par la Feldgendarmerie (police militaire allemande). La Kommandantur s'installe en ville. Pendant quatre ans, Sens vivra sous l'occupation -- rationnement, couvre-feu, arrestations, travail obligatoire.\n\nCe qui frappe dans les temoignages, c'est la rapidite de l'effondrement. En six semaines, la France de 1940 s'ecroule. Pour les Senonais, le choc est immense -- la generation de leurs peres avait tenu quatre ans dans les tranchees."
}

idx = 0
applied = 0
for ch in data["chapters"]:
    for ev in ch["events"]:
        if idx in missing:
            ev["longText"] = missing[idx]
            applied += 1
        idx += 1

with open(main_path, "w", encoding="utf-8") as f:
    json.dump(data, f, ensure_ascii=False, indent=2)

total_lt = sum(1 for ch in data["chapters"] for ev in ch["events"] if ev.get("longText"))
total_ev = sum(len(ch["events"]) for ch in data["chapters"])
print(f"Applied {applied} missing longTexts")
print(f"TOTAL: {total_lt}/{total_ev} events with longText")
